CREATE SCHEMA user_details;

CREATE SCHEMA journey;

GRANT CONNECT ON SCHEMA user_details TO APP_MIGRATION_SERVICE_EFN;

GRANT CONNECT ON SCHEMA user_details TO APP_SYSTEM_SERVICE_EFN;

GRANT CONNECT ON SCHEMA journey TO APP_MIGRATION_SERVICE_EFN;

GRANT CONNECT ON SCHEMA journey TO APP_SYSTEM_SERVICE_EFN;