CREATE USER APP_SIGNUP_SERVICE_EFN WITH LOGIN PASSWORD'cfe19f1c-81e8-42aa-8ece-cad1de3a1419';
CREATE USER APP_CORE_SERVICE_EFN WITH LOGIN PASSWORD'3bd8e947-8b89-4a65-9c37-941a10cc31e1';
CREATE USER APP_DATA_SERVICE_EFN WITH LOGIN PASSWORD'0dcd1be1-d3aa-4b55-8992-a129c5767cd7';
CREATE USER APP_ALEMBIC_EFN WITH LOGIN PASSWORD'a6b92993-36cd-46c5-b11d-f66d9d4ecc5b';
CREATE ROLE APP_SYSTEM_SERVICE_EFN WITH NOLOGIN;
CREATE ROLE APP_MIGRATION_SERVICE_EFN WITH NOLOGIN;

CREATE DATABASE signup;

CREATE DATABASE core;

GRANT CONNECT ON DATABASE signup TO APP_MIGRATION_SERVICE_EFN;

GRANT CONNECT ON DATABASE signup TO APP_SYSTEM_SERVICE_EFN;

GRANT CONNECT ON DATABASE core TO APP_MIGRATION_SERVICE_EFN;

GRANT CONNECT ON DATABASE core TO APP_SYSTEM_SERVICE_EFN;

