DROP ROLE APP_SIGNUP_SERVICE_EFN;
DROP USER APP_CORE_SERVICE_EFN;
DROP USER APP_DATA_SERVICE_EFN;
DROP USER APP_ALEMBIC_EFN;

DROP ROLE APP_SYSTEM_SERVICE_EFN ;
DROP ROLE APP_MIGRATION_SERVICE_EFN ;

DROP DATABASE signup;

DROP DATABASE core;

DROP USER CROSS_DATABASE_USER;
