CREATE USER APP_SIGNUP_SERVICE_EFN WITH LOGIN PASSWORD 'senh@segUr@1';
CREATE USER APP_CORE_SERVICE_EFN WITH LOGIN PASSWORD'senh@segUr@1';
CREATE USER APP_DATA_SERVICE_EFN WITH LOGIN PASSWORD'senh@segUr@1';
CREATE USER APP_ALEMBIC_EFN WITH LOGIN PASSWORD'senh@segUr@1';
CREATE USER CROSS_DATABASE_USER WITH LOGIN PASSWORD 'senh@segUr@1';

CREATE ROLE APP_SYSTEM_SERVICE_EFN WITH NOLOGIN;
CREATE ROLE APP_MIGRATION_SERVICE_EFN WITH NOLOGIN;
CREATE ROLE replica WITH REPLICATION PASSWORD 'senh@segUr@1' LOGIN;

CREATE DATABASE signup;

CREATE DATABASE core;

GRANT CONNECT ON DATABASE signup TO APP_MIGRATION_SERVICE_EFN;

GRANT CONNECT ON DATABASE signup TO APP_SYSTEM_SERVICE_EFN;

GRANT CONNECT ON DATABASE core TO APP_MIGRATION_SERVICE_EFN;

GRANT CONNECT ON DATABASE core TO APP_SYSTEM_SERVICE_EFN;

GRANT CONNECT ON DATABASE signup TO CROSS_DATABASE_USER;

GRANT CONNECT ON DATABASE core TO CROSS_DATABASE_USER;
